### PR TITLE
Lesson1 8

### PR DESCRIPTION
**Pull request by NatachaKey**

### CODE REVIEW

**Review by GinaCastromonte — CHANGES_REQUESTED** [review]
There was an issue with the POST request , I wasn't sure if you were getting it on your end.  Also, there's no need for local storage now that we are working with APIs but you can certainly still implement it.  Let me know if you would like more guidance

**Comment by NatachaKey** [comment]
hi @GinaCastromonte , I still get the issue with POST request - the date is not being saved to a db in ISO format- is it a bug?

**Comment by NatachaKey** [comment]
@GinaCastromonte moreover, now It doesn't save any data at all after user's input , I regenerated the token and checked base ID of the airtable but still doesn't work 
image

**Comment by NatachaKey** [comment]
@GinaCastromonte 
image

**Pull request merged**
